// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package structfields

// Injectors from wire.go:

func InitializeMessage(phrase string, code int) Content {
	message := NewMessage(phrase, code)
	content := message.Content
	return content
}
