// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bindinginterfaces

import (
	"io"
	"os"
)

// Injectors from wire.go:

func InitializeWriter() io.Writer {
	writer := _wireFileValue
	return writer
}

var (
	_wireFileValue = os.Stdout
)
