// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/gin-gonic/gin"
	"github.com/jianghushinian/blog-go-example/wire/user/internal/biz"
	"github.com/jianghushinian/blog-go-example/wire/user/internal/config"
	"github.com/jianghushinian/blog-go-example/wire/user/internal/controller"
	"github.com/jianghushinian/blog-go-example/wire/user/internal/store"
	"github.com/jianghushinian/blog-go-example/wire/user/pkg/db"
)

// Injectors from wire.go:

func wireApp(engine *gin.Engine, cfg *config.Config, mysqlOptions *db.MySQLOptions) (*App, func(), error) {
	gormDB, cleanup, err := db.NewMySQL(mysqlOptions)
	if err != nil {
		return nil, nil, err
	}
	userStore := store.New(gormDB)
	userBiz := biz.New(userStore)
	userController := controller.New(userBiz)
	app := &App{
		Config: cfg,
		g:      engine,
		uc:     userController,
	}
	return app, func() {
		cleanup()
	}, nil
}
