// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package multi

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

// InitializeApp 初始化 App
func InitializeApp() (*App, func(), error) {
	db, cleanup, err := NewDatabaseConnection()
	if err != nil {
		return nil, nil, err
	}
	file, cleanup2, err := NewLogFile()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := &App{
		DB:  db,
		Log: file,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
