// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cleanupfunctions

import (
	"os"
)

// Injectors from wire.go:

func InitializeFile(path string) (*os.File, func(), error) {
	file, cleanup, err := OpenFile(path)
	if err != nil {
		return nil, nil, err
	}
	return file, func() {
		cleanup()
	}, nil
}
