// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package structproviders

// Injectors from wire.go:

func InitializeEvent(phrase string, code int) (Event, error) {
	message := Message{
		Content: phrase,
	}
	greeter := NewGreeter(message)
	event, err := NewEvent(greeter)
	if err != nil {
		return Event{}, err
	}
	return event, nil
}
