// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bindingstruct

// Injectors from wire.go:

func WireRunStore(msg *Message) error {
	bindingstructStore := New()
	error2 := SaveMessage(bindingstructStore, msg)
	return error2
}
