// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package alternateinjectorsyntax

// Injectors from wire.go:

func InitializeMessage(phrase string) Message {
	message := NewMessage(phrase)
	return message
}
